#!/usr/bin/env bash
set -euo pipefail

# Generated by run.sh __RUN_VERSION__ on __RUN_GENERATED_AT__.
# DO NOT EDIT THIS FILE — re-run install.sh to regenerate it.
# Your customizations belong in .runrc and __RUN_TASK_DIR_NAME__/*.sh (never touched by re-install).

TASK_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TASK_DIR="$TASK_ROOT/__RUN_TASK_DIR_NAME__"

require_tool() {
  local cmd="$1" msg="$2"
  command -v "$cmd" >/dev/null 2>&1 || { echo "error: $msg" >&2; exit 1; }
}

# shellcheck source=/dev/null
. "$TASK_ROOT/.runrc"

depends_on() {
  local task
  for task in "$@"; do
    "$TASK_ROOT/run" "$task" || return $?
  done
}

cmd_list() {
  printf '\n'
  run_gradient_text "run.sh" 2>/dev/null || printf 'run.sh'
  printf ' — tasks in this project\n\n'
  local f name
  for f in "$TASK_DIR"/*.sh; do
    [ -e "$f" ] || continue
    name="$(basename "$f" .sh)"
    # shellcheck disable=SC1090
    printf '  %-15s %s\n' "$name" "$(. "$f"; description)"
  done
  printf '\n'
}

cmd_help() {
  local task="${1:-}"
  if [ -z "$task" ] || [ ! -f "$TASK_DIR/$task.sh" ]; then
    echo "error: unknown task '$task'" >&2
    cmd_list >&2
    exit 1
  fi
  # shellcheck disable=SC1090
  . "$TASK_DIR/$task.sh"
  description
  echo
  help
}

cmd_new() {
  local name="${1:-}"
  case "$name" in
    "") echo "usage: ./run new <task-name>" >&2; return 1 ;;
    run) echo "error: 'run' is reserved (the dispatcher script)" >&2; return 1 ;;
    *[!a-zA-Z0-9_-]*) echo "error: task name must be alnum/underscore/hyphen" >&2; return 1 ;;
  esac
  local target="$TASK_DIR/$name.sh"
  if [ -e "$target" ] && [ "${2:-}" != "--force" ]; then
    echo "error: $target already exists (use --force to overwrite)" >&2
    return 1
  fi
  cat > "$target" <<TASK_BOILERPLATE
#!/usr/bin/env bash
# Sourced by ./run — do not execute directly.

description() {
  echo "TODO: one-line description of $name"
}

help() {
  cat <<'EOF'
Usage: ./run $name [args...]

TODO: describe usage.
EOF
}

main() {
  echo "TODO: implement $name"
}
TASK_BOILERPLATE
  run_gradient_text "created" 2>/dev/null || printf 'created'
  printf ' %s\n' "$target"
}

case "${1:-}" in
  "") cmd_list ;;
  help) shift; cmd_help "$@" ;;
  new)  shift; cmd_new "$@" ;;
  *)
    task="$1"; shift
    if [ ! -f "$TASK_DIR/$task.sh" ]; then
      echo "error: unknown task '$task'" >&2
      cmd_list >&2
      exit 1
    fi
    # shellcheck disable=SC1090
    . "$TASK_DIR/$task.sh"
    main "$@"
    ;;
esac
