#!/usr/bin/env bash
set -euo pipefail

# Generated by run.sh __RUN_VERSION__ on __RUN_GENERATED_AT__.
# DO NOT EDIT THIS FILE — re-run install.sh to regenerate it.
# Your customizations belong in .runrc and __RUN_TASK_DIR_NAME__/*.sh (never touched by re-install).

TASK_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TASK_DIR="$TASK_ROOT/__RUN_TASK_DIR_NAME__"

require_tool() {
  local cmd="$1" msg="$2"
  command -v "$cmd" >/dev/null 2>&1 || { echo "error: $msg" >&2; exit 1; }
}

# shellcheck source=/dev/null
. "$TASK_ROOT/.runrc"

depends_on() {
  local task
  for task in "$@"; do
    "$TASK_ROOT/run" "$task" || return $?
  done
}

cmd_list() {
  printf '\n'
  run_color_echo neon "run.sh" 2>/dev/null || printf 'run.sh'
  printf ' — tasks in this project\n\n'
  local f name has_tasks=0
  for f in "$TASK_DIR"/*.sh; do
    [ -e "$f" ] || continue
    has_tasks=1
    name="$(basename "$f" .sh)"
    # shellcheck disable=SC1090
    printf '  %-15s %s\n' "$name" "$(. "$f"; description)"
  done
  if [ "$has_tasks" -eq 0 ]; then
    printf '  No tasks yet.\n\n'
    printf '  Create your first task by adding a file at %s/<name>.sh:\n\n' "$(basename "$TASK_DIR")"
    printf '    #!/usr/bin/env bash\n'
    printf '    description() { echo "One-line summary"; }\n'
    printf '    help() { echo "Usage: ./run <name> [args...]"; }\n'
    printf '    main() { echo "task logic goes here, receives \\"$@\\""; }\n\n'
    printf '  Or scaffold examples with: bash install.sh --examples\n'
  fi
  printf '\n'
}

case "${1:-}" in
  "") cmd_list ;;
  *)
    task="$1"; shift
    if [ ! -f "$TASK_DIR/$task.sh" ]; then
      echo "error: unknown task '$task'" >&2
      cmd_list >&2
      exit 1
    fi
    # shellcheck disable=SC1090
    . "$TASK_DIR/$task.sh"
    main "$@"
    ;;
esac
